version: '3'
services:
  backend:
    restart: always
    image: justtill/easy-stocks:latest
    ports:
      - "8080:8080"
    container_name: easystocksbackend
    environment:
      - POSTGRES_PW=postgres # ${POSTGRES_PW}
      - POSTGRES_USER=postgres # ${POSTGRES_USER}
      - POSTGRES_HOST=db # ${POSTGRES_HOST}
      - POSTGRES_PORT=5432 # ${POSTGRES_PORT}
      - POSTGRES_DATABASE=postgres #${POSTGRES_DATABASE}
      - STOCK_APIKEY=fsddsfsddsf #${STOCK_APIKEY}
      - INIT_HISTORY=false #${INIT_HISTORY}
      - INTERVAL=3 #${INTERVAL}
      - PERCENTAGE=2.1 #${PERCENTAGE}
    depends_on:
      - db
  db:
    restart: always
    image: postgres:14.0-alpine
    container_name: easystocksdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres #${POSTGRES_PW}
      - POSTGRES_USER=postgres #${POSTGRES_USER}
      - POSTGRES_DB=easystocks #${POSTGRES_DATABASE}
    ports:
      - 5431:5431
volumes:
  postgres_data: